version: "3"
services:
  dockermongodb:
    image: mongo:latest
    container_name: "dockermongodb"
    ports:
      - 27017:27017
  pauta-service:
    image: pauta-service
    container_name: "pauta-service"
    ports:
      - 7080:7080
    links:
      - dockermongodb
